import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './styles/index.css'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home - Hello',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }){
  let darkMode = false

  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen relative ${ darkMode ? "dark" : "" }`}>
        <Header />
        { children }
      </body>
    </html>
  )
}